#!/bin/bash
#
#   CDM: The Console Display Manager
#
#   Copyright (C) 2009-2012, Daniel J Griffiths <dgriffiths@ghost1227.com>
#   Thanks to:
#
#       Andrwe          beta-testing and submitting the fix for the all
#                       important X incrementation function
#       brisbin33       code cleanup
#       tigrmesh        finding a critical issue with the gnome-session handler
#       Profjim         several incredibly useful patches
#       lambchops468    hibernation patches
#       CasperVector    Massive rearchitecturing and code sanisation
#
#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#   
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
#   
#   You should have received a copy of the GNU General Public License
#   along with this program; if not, write to the Free Software
#   Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#   MA 02110-1301, USA.

name=$(basename "$0")
altstartx=false
startxlog=/dev/null

info() { printf ' \033[01;32m*\033[00m '; echo "$name: $*"; }
error() { (printf ' \033[01;31m*\033[00m '; echo "$name: $*") > /dev/stderr; }

args=$(getopt -n "$name" -o ct: -l altstartx,startxlog: -- "$@") || exit 1
eval set -- "$args"
for arg in "$@"
do
    case $arg in
        '--altstartx')
            altstartx=true; shift
            ;;
        '--startxlog')
            shift
            startxlog=$1; shift
            ;;
        '--')
            shift
            break
            ;;
    esac
done

if $altstartx; then
    # Alternative method of calling setsid(/startx) for systems that are unresponsive to the 'normal' call.
    (setsid startx "$@" > "$startxlog" 2>&1 &)
else
    setsid startx "$@" > "$startxlog" 2>&1 &
fi

# vim:ts=4:sw=4:et
